export const routes = {
  LOGIN: '/login',
  REGISTER: '/register',
  APP: '/app',
  CUSTODIANS: '/app/custodians',
  USER_MANAGEMENT: '/app/profile/users',
  CURRENT_USERS: '/app/profile/users/current-users',
  USER_GROUPS: '/app/profile/users/groups',
  ABOUT_PLATFORM: '/app/about-platform',
  PRIVACY_POLICY: '/app/privacy-policy',
  ITEMS: '/app/items',
  TRACKERS: '/app/trackers',
  SHIPMENT: '/app/shipment',
  RESET_PASSWORD: '/reset-password',
  RESET_PASSWORD_CONFIRM: '/reset-password-confirm',
  REPORTING: '/app/reporting',
  ADMIN_PANEL: '/app/admin-panel',
  CONFIGURATION: '/app/admin-panel/configuration',
  // IMPORT_EXPORT: '/app/admin-panel/import-export',
  CONSORTIUM: '/app/admin-panel/consortium',
  CREATE_SHIPMENT: '/app/create-shipment',
};
