export const routes = {
  HOME: '/',
  LOGIN: '/login',
  REGISTER: '/register',
  FORGOT_PASSWORD: '/forgot-password',
  RESET_PASSWORD: '/reset-password-confirm',
  VERIFY_EMAIL: '/verify-email',
  APP: '/app',
  DASHBOARD: '/app/dashboard',
  DASHBOARD_TABULAR: '/app/dashboard/tabular',
  DASHBOARD_KANBAN: '/app/dashboard/kanban',
  DASHBOARD_REPORT: '/app/dashboard/report',
  USER_MANAGEMENT: '/app/profile/users',
  CURRENT_USERS: '/app/profile/users/current-users',
  USER_GROUPS: '/app/profile/users/groups',
  HELP: '/help',
  TICKET_STATUS: '/ticket-status',
  MISSING_DATA: '/missing-data',
  NEW_PRODUCT: '/app/new-product',
  RELEASE: '/app/release',
  DEVELOPER_FORM: '/app/developer-form',
  PRODUCTS: '/app/products',
};
