export const routes = {
  LOGIN: "/login",
  REGISTER: "/register",
  APP: "/app",
  DASHBOARD: "/app/dashboard",
  CUSTODIANS: "/app/custodians",
  USER_MANAGEMENT: "/app/profile/users",
  CURRENT_USERS: "/app/profile/users/current-users",
  USER_GROUPS: "/app/profile/users/groups",
  MY_ACCOUNT: "/app/account",
  ITEMS: "/app/items",
  SENSORS_GATEWAY: "/app/sensors-gateway",
  SHIPMENT: "/app/shipment",
  RESET_PASSWORD: "/reset-password",
  RESET_PASSWORD_CONFIRM: "/reset-password-confirm",
  REPORTING: "/app/reporting",
};
