export const RECALL_DATA = [
  {
    shipmentId: "10000",
    issue: "recall",
    affected: "2000",
    custodian: "CN01222",
  },
  {
    shipmentId: "20000",
    issue: "recall",
    affected: "2000",
    custodian: "CN01222",
  },
  {
    shipmentId: "30000",
    issue: "recall",
    affected: "2000",
    custodian: "CN01222",
  },
  {
    shipmentId: "40000",
    issue: "recall",
    affected: "2000",
    custodian: "CN01222",
  },
];

export const DELAY_DATA = [
  {
    shipmentId: "10000",
    delay: "74",
    itemNo: "400",
    risk: "100000",
    custodian: "CN01222",
  },
  {
    shipmentId: "10000",
    delay: "74",
    itemNo: "400",
    risk: "100000",
    custodian: "CN01222",
  },
  {
    shipmentId: "10000",
    delay: "74",
    itemNo: "400",
    risk: "100000",
    custodian: "CN01222",
  },
  {
    shipmentId: "10000",
    delay: "74",
    itemNo: "400",
    risk: "100000",
    custodian: "CN01222",
  },
];

export const CUSTODIAN_DATA = [
  {
    name: "Nicole",
    id: 1,
    contact_data: "Arizona, Newyork",
    custodian_glns: "GLN123456",
    currentShipments: "SH123456, ABC23456",
  },
  {
    name: "Adam",
    id: 2,
    contact_data: "Arizona, Newyork",
    custodian_glns: "GLN123456",
    currentShipments: "SH123456, ABC23456",
  },
  {
    name: "Cathy",
    id: 3,
    contact_data: "Arizona, Newyork",
    custodian_glns: "GLN123456",
    currentShipments: "SH123456, ABC23456",
  },
];

export const COUNTRY_CHOICES = ["USA"];

export const STATE_CHOICES = [
  "AL",
  "AZ",
  "AR",
  "CA",
  "CO",
  "CT",
  "DE",
  "DC",
  "FL",
  "GA",
  "ID",
  "IL",
  "IN",
  "IA",
  "KS",
  "KY",
  "LA",
  "ME",
  "MD",
  "MA",
  "MI",
  "MN",
  "MS",
  "MO",
  "MT",
  "NE",
  "NV",
  "NH",
  "NJ",
  "NM",
  "NY",
  "NC",
  "ND",
  "OH",
  "OK",
  "OR",
  "PA",
  "RI",
  "SC",
  "SD",
  "TN",
  "TX",
  "UT",
  "VT",
  "VA",
  "WA",
  "WV",
  "WI",
  "WY",
  "AK",
  "HI",
];

export const ADDRESS_TYPE = [
  "home",
  "billing",
  "business",
  "delivery",
  "mailing",
];

export const SHIPMENT_STATUS = [
  { value: "Planned", label: "Planned" },
  { value: "Enroute", label: "Enroute" },
  { value: "Cancelled", label: "Cancelled" },
  { value: "Completed", label: "Completed" },
];

export const TRANSPORT_MODE = [
  { value: "Air", label: "Air" },
  { value: "sea", label: "Sea" },
  { value: "land-rail", label: "Land Rail" },
  { value: "land-road", label: "Land Road" },
  { value: "mixed", label: "Mixed" },
];

export const associatedGatewayMock = [
  { id: 1, uuid: "GT123456", name: "Gateway 1" },
  { id: 1, uuid: "GT123457", name: "Gateway 2" },
  { id: 1, uuid: "GT123459", name: "Gateway 3" },
  { id: 1, uuid: "GT123458", name: "Gateway 4" },
  { id: 1, uuid: "GT123455", name: "Gateway 5" },
];

export const shipmentMock = [
  {
    id: "SH123214",
    url: "string",
    grai: "string",
    name: "Komal Shipment 1",
    sscc: "string",
    status: "Enroute",
    load_id: "1234",
    item_ids: ["1", "2"],
    net_weight: 0,
    wallet_ids: ["string"],
    gateway_ids: ["1", "2"],
    recall_flag: false,
    ship_to_gln: "string",
    tare_weight: 0,
    bol_order_id: "string",
    gross_weight: 0,
    custodian_ids: ["string"],
    ship_from_gln: "string",
    excursion_flag: true,
    transport_mode: "string",
    actual_distance: 0,
    unit_of_measure: "string",
    max_warning_temp: 40,
    min_warning_temp: 10,
    planned_distance: 0,
    route_description: "abc",
    sensor_report_ids: ["1", "2"],
    max_excursion_temp: 70,
    min_excursion_temp: 1,
    warehouse_location: "string",
    max_warning_humidity: 60,
    min_warning_humidity: 20,
    actual_time_of_arrival: "2020-06-19T08:03:25.185Z",
    max_excursion_humidity: 80,
    min_excursion_humidity: 10,
    actual_time_of_departure: "2020-06-2T08:03:25.185Z",
    estimated_time_of_arrival: "2020-06-19T08:03:25.185Z",
    estimated_time_of_departure: "2020-06-4T08:03:25.185Z",
  },
  {
    id: "SH127654",
    url: "string",
    grai: "string",
    name: "Komal Shipment 2",
    sscc: "string",
    status: "Enroute",
    load_id: "1234",
    item_ids: ["1", "2"],
    net_weight: 0,
    wallet_ids: ["string"],
    gateway_ids: ["1", "2"],
    recall_flag: false,
    ship_to_gln: "string",
    tare_weight: 0,
    bol_order_id: "string",
    gross_weight: 0,
    custodian_ids: ["string"],
    ship_from_gln: "string",
    excursion_flag: true,
    transport_mode: "string",
    actual_distance: 0,
    unit_of_measure: "string",
    max_warning_temp: 40,
    min_warning_temp: 10,
    planned_distance: 0,
    route_description: "abc",
    sensor_report_ids: ["1", "2"],
    max_excursion_temp: 70,
    min_excursion_temp: 1,
    warehouse_location: "string",
    max_warning_humidity: 60,
    min_warning_humidity: 20,
    actual_time_of_arrival: "2020-06-15T08:03:25.185Z",
    max_excursion_humidity: 80,
    min_excursion_humidity: 10,
    actual_time_of_departure: "2020-06-2T08:03:25.185Z",
    estimated_time_of_arrival: "2020-06-19T08:03:25.185Z",
    estimated_time_of_departure: "2020-06-4T08:03:25.185Z",
  },
  {
    id: "SH11209466",
    url: "string",
    grai: "string",
    name: "Shipment 1",
    sscc: "string",
    status: "Enroute",
    load_id: "1234",
    item_ids: ["1", "2"],
    net_weight: 0,
    wallet_ids: ["string"],
    gateway_ids: ["1", "2"],
    recall_flag: false,
    ship_to_gln: "string",
    tare_weight: 0,
    bol_order_id: "string",
    gross_weight: 0,
    custodian_ids: ["string"],
    ship_from_gln: "string",
    excursion_flag: true,
    transport_mode: "string",
    actual_distance: 0,
    unit_of_measure: "string",
    max_warning_temp: 40,
    min_warning_temp: 10,
    planned_distance: 0,
    route_description: "abc",
    sensor_report_ids: ["1", "2"],
    max_excursion_temp: 70,
    min_excursion_temp: 1,
    warehouse_location: "string",
    max_warning_humidity: 60,
    min_warning_humidity: 20,
    actual_time_of_arrival: "2020-06-18T08:03:25.185Z",
    max_excursion_humidity: 80,
    min_excursion_humidity: 10,
    actual_time_of_departure: "2020-06-2T08:03:25.185Z",
    estimated_time_of_arrival: "2020-06-19T08:03:25.185Z",
    estimated_time_of_departure: "2020-06-4T08:03:25.185Z",
  },
  {
    id: "SH12345121",
    url: "string",
    grai: "string",
    name: "Shipment 2",
    sscc: "string",
    status: "Enroute",
    load_id: "1234",
    item_ids: ["1", "2"],
    net_weight: 0,
    wallet_ids: ["string"],
    gateway_ids: ["1", "2"],
    recall_flag: false,
    ship_to_gln: "string",
    tare_weight: 0,
    bol_order_id: "string",
    gross_weight: 0,
    custodian_ids: ["string"],
    ship_from_gln: "string",
    excursion_flag: true,
    transport_mode: "string",
    actual_distance: 0,
    unit_of_measure: "string",
    max_warning_temp: 40,
    min_warning_temp: 10,
    planned_distance: 0,
    route_description: "abc",
    sensor_report_ids: ["1", "2"],
    max_excursion_temp: 70,
    min_excursion_temp: 1,
    warehouse_location: "string",
    max_warning_humidity: 60,
    min_warning_humidity: 20,
    actual_time_of_arrival: "2020-06-26T08:03:25.185Z",
    max_excursion_humidity: 80,
    min_excursion_humidity: 10,
    actual_time_of_departure: "2020-06-2T08:03:25.185Z",
    estimated_time_of_arrival: "2020-06-19T08:03:25.185Z",
    estimated_time_of_departure: "2020-06-4T08:03:25.185Z",
  },
  {
    id: "SH12345867",
    url: "string",
    grai: "string",
    name: "Shipment 3",
    sscc: "string",
    status: "Enroute",
    load_id: "1234",
    item_ids: ["1", "2"],
    net_weight: 0,
    wallet_ids: ["string"],
    gateway_ids: ["1", "2"],
    recall_flag: false,
    ship_to_gln: "string",
    tare_weight: 0,
    bol_order_id: "string",
    gross_weight: 0,
    custodian_ids: ["string"],
    ship_from_gln: "string",
    excursion_flag: true,
    transport_mode: "string",
    actual_distance: 0,
    unit_of_measure: "string",
    max_warning_temp: 40,
    min_warning_temp: 10,
    planned_distance: 0,
    route_description: "abc",
    sensor_report_ids: ["1", "2"],
    max_excursion_temp: 70,
    min_excursion_temp: 1,
    warehouse_location: "string",
    max_warning_humidity: 60,
    min_warning_humidity: 20,
    actual_time_of_arrival: "2020-06-25T08:03:25.185Z",
    max_excursion_humidity: 80,
    min_excursion_humidity: 10,
    actual_time_of_departure: "2020-06-2T08:03:25.185Z",
    estimated_time_of_arrival: "2020-06-19T08:03:25.185Z",
    estimated_time_of_departure: "2020-06-4T08:03:25.185Z",
  },
  {
    id: "SH123452321",
    url: "string",
    grai: "string",
    name: "Shipment 4",
    sscc: "string",
    status: "Planned",
    load_id: "1234",
    item_ids: ["1", "2"],
    net_weight: 0,
    wallet_ids: ["string"],
    gateway_ids: ["1", "2"],
    recall_flag: false,
    ship_to_gln: "string",
    tare_weight: 0,
    bol_order_id: "string",
    gross_weight: 0,
    custodian_ids: ["string"],
    ship_from_gln: "string",
    excursion_flag: true,
    transport_mode: "string",
    actual_distance: 0,
    unit_of_measure: "string",
    max_warning_temp: 40,
    min_warning_temp: 10,
    planned_distance: 0,
    route_description: "abc",
    sensor_report_ids: ["1", "2"],
    max_excursion_temp: 70,
    min_excursion_temp: 1,
    warehouse_location: "string",
    max_warning_humidity: 60,
    min_warning_humidity: 20,
    actual_time_of_arrival: "2020-06-16T08:03:25.185Z",
    max_excursion_humidity: 80,
    min_excursion_humidity: 10,
    actual_time_of_departure: "2020-06-10T08:03:25.185Z",
    estimated_time_of_arrival: "2020-06-10T08:03:25.185Z",
    estimated_time_of_departure: "2020-06-6T08:03:25.185Z",
  },
];
