export const GET_API_RESPONSE = "IMPORT-EXPORT/GET_API_RESPONSE";
export const GET_API_RESPONSE_SUCCESS = "IMPORT-EXPORT/GET_API_RESPONSE_SUCCESS";
export const GET_API_RESPONSE_FAILURE = "IMPORT-EXPORT/GET_API_RESPONSE_FAILURE";

export const getApiResponse = (url, header) => ({
  type: GET_API_RESPONSE,
  url,
  header,
});